version: 2.1

description: |
    A sample CircleCI config file that uses the ryanshoover/wpengine orb
    to test a site repo at every stage and deploy the site to WP Engine environments.

orbs:
    wpengine: ryanshoover/wpengine@0.3

workflows:
    version: 2

    build_test_deploy:
        jobs:
            - wpengine/lint
            - wpengine/codeception

            - wpengine/build_deploy:
                name:         deploy-development
                environment:  development
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only: development

            - wpengine/build_deploy:
                name:         deploy-staging
                environment:  staging
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only: staging

            - wpengine/build_deploy:
                name:         deploy-production
                environment:  production
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only:
                            - master
                            - production
            - wpengine/build_deploy:
                name:         deploy-feature
                environment:  thenameofmyfeatureinstall
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only:
                            - /feat-.*/


    regression:
        jobs:
            - wpengine/backstop:
                config: tests/_backstop/index.js
                filters:
                    branches:
                        only:
                            - staging
