description: |
    Build a plugin, theme, or site. Installs composer and yarn dependencies. Runs yarn build command.

executor: php

steps:
    - checkout

    # Composer Cache and Install
    - restore_cache:
        keys:
            - composer-{{ .Environment.CACHE_VERSION }}-{{ checksum "composer.lock" }}
    - run:
        name: Install composer dependencies
        command: |
          if [ -f composer.lock ]; then
              composer install --no-ansi --no-interaction --no-progress --optimize-autoloader --prefer-dist
          fi
    - save_cache:
        paths:
            - ./vendor
        key: composer-{{ .Environment.CACHE_VERSION }}-{{ checksum "composer.lock" }}

    # Add debug step here, before any cache operations
    - run:
        name: Debug Theme Path
        command: |
            echo "THEME_PATH is set to: $THEME_PATH"
            echo "Current directory:"
            pwd
            echo "Directory contents:"
            ls -la
            echo "Theme directory contents (if exists):"
            ls -la $THEME_PATH || echo "Theme path not found"
            echo "Looking for package-lock.json:"
            ls -la ${THEME_PATH}/package-lock.json || echo "package-lock.json not found"

    # NPM Cache and Install from the theme path
    - restore_cache:
        keys:
            - npm-{{ .Environment.CACHE_VERSION }}-{{ checksum "${THEME_PATH}/package-lock.json" }}
    - run:
        name: Install node dependencies
        command: |
            if [ -f ${THEME_PATH}/package-lock.json ]; then
                npm --prefix $THEME_PATH install
            fi
    - save_cache:
        paths:
            - ${THEME_PATH}/node_modules  # Changed to match install location
        key: npm-{{ .Environment.CACHE_VERSION }}-{{ checksum "${THEME_PATH}/package-lock.json" }}

    # Build step
    - run:
        name: Build compiled files
        command: |
            if jq -e '.scripts.build' ${THEME_PATH}/package.json; then
                npm --prefix $THEME_PATH run build
            fi

    - persist_to_workspace:
        root: /home/circleci/project
        paths:
            - .
